<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class PegawaiLogin extends CI_Controller{
 
	function __construct(){
		parent::__construct();		
		$this->load->model('mPegawai_login');
 
	}
 
	function index(){
		$this->load->view('vPegawai_login');
	}
 
	function aksi_login(){
		$nama_pegawai = $this->input->post('nama_pegawai');
		$password = $this->input->post('password');
		$where = array(
			'nama_pegawai' => $nama_pegawai,
			'password' => $password
			);
		$cek = $this->mPegawai_login->cek_login("pegawai",$where)->num_rows();
		if($cek > 0){
 
			$data_session = array(
				'nama' => $nama_pegawai,
				'status' => "login"
				);
 
			$this->session->set_userdata($data_session);
 
			redirect(base_url("barangpegawai"));
 
		}else{
			echo "Username dan password salah !";
		}
	}
 
	function logout(){
		$this->session->sess_destroy();
		redirect(base_url('home'));
	}
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */